name: Build & Push Worker Image

on:
  push:
    branches:
      - main  # runs this workflow when you push to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Set up Java (same version as your project)
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3️⃣ Build the jar using Gradle
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build jar
        run: ./gradlew clean build

      # 4️⃣ Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 5️⃣ Build & push Docker image
      - name: Build & Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: krauserkane/codebench-worker:latest
